import MainMenu from '@/components/MainMenu/MainMenu'
import './global.css'

import StoreProvider from '@/providers/StoreProvider'
import type { Metadata } from 'next'
import ThemeToggle from '@/components/ThemeToggle/ThemeToggle'
import ThemeContextProvider from '@/providers/context/ThemeContext';


export const metadata: Metadata = {
  title: 'Server Side Rendering',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ThemeContextProvider>
      <html lang="en">
        <body>
          <ThemeToggle />

          <MainMenu />

          <StoreProvider>
            {children}
            </StoreProvider>
        </body>
      </html>
    </ThemeContextProvider>
  )
}
