import MainMenu from '@/components/MainMenu/MainMenu'
import './global.css'

import StoreProvider from '@/providers/StoreProvider'
import type { Metadata } from 'next'
import ThemeToggle from '@/components/ThemeToggle/ThemeToggle'

import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import LanguageToggle from '@/components/LanguageToggle/LanguageToggle'
import Main from '@/components/Main'

export const metadata: Metadata = {
  title: 'Server Side Rendering',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const { locale } = await params
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body>
        <ThemeToggle />

        <NextIntlClientProvider locale={locale} messages={messages}>
          <LanguageToggle />

          <MainMenu />

          <StoreProvider>
            <Main>{children}</Main>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
